version: "3"

services:
  minio2:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - 'minio_data:/data'
    environment:
      MINIO_ROOT_USER: chatwards
      MINIO_ROOT_PASSWORD: chatwards
      MINIO_DEFAULT_BUCKETS: chatwards

    command: server --console-address ":9001" /data

volumes:
  minio_data:
    driver: local
